 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/resolutions", type: :request do
  
  # Resolution. As you add validations to Resolution, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Resolution.create! valid_attributes
      get resolutions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      resolution = Resolution.create! valid_attributes
      get resolution_url(resolution)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_resolution_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      resolution = Resolution.create! valid_attributes
      get edit_resolution_url(resolution)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Resolution" do
        expect {
          post resolutions_url, params: { resolution: valid_attributes }
        }.to change(Resolution, :count).by(1)
      end

      it "redirects to the created resolution" do
        post resolutions_url, params: { resolution: valid_attributes }
        expect(response).to redirect_to(resolution_url(Resolution.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Resolution" do
        expect {
          post resolutions_url, params: { resolution: invalid_attributes }
        }.to change(Resolution, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post resolutions_url, params: { resolution: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested resolution" do
        resolution = Resolution.create! valid_attributes
        patch resolution_url(resolution), params: { resolution: new_attributes }
        resolution.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the resolution" do
        resolution = Resolution.create! valid_attributes
        patch resolution_url(resolution), params: { resolution: new_attributes }
        resolution.reload
        expect(response).to redirect_to(resolution_url(resolution))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        resolution = Resolution.create! valid_attributes
        patch resolution_url(resolution), params: { resolution: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested resolution" do
      resolution = Resolution.create! valid_attributes
      expect {
        delete resolution_url(resolution)
      }.to change(Resolution, :count).by(-1)
    end

    it "redirects to the resolutions list" do
      resolution = Resolution.create! valid_attributes
      delete resolution_url(resolution)
      expect(response).to redirect_to(resolutions_url)
    end
  end
end
